/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/ARwtsrrLw54
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Tenor_Sans } from 'next/font/google'
import { Chivo } from 'next/font/google'

tenor_sans({
  subsets: ['latin'],
  display: 'swap',
})

chivo({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link";
import { Avatar, AvatarImage, AvatarFallback } from "@/components/ui/avatar";
import { Button } from "@/components/ui/button";

export default function Page() {
  return (
    <div className="flex flex-col min-h-screen bg-background">
      <header className="flex items-center justify-between px-6 py-4 border-b">
        <Link href="#" className="flex items-center gap-2" prefetch={false}>
          <MessageSquareIcon className="w-6 h-6" />
          <span className="text-lg font-semibold">
            Mental Health Consultation
          </span>
        </Link>
      </header>
      <main className="flex-1 px-4 py-12 md:py-24">
        <div className="max-w-7xl mx-auto">
          <div className="bg-background rounded-lg shadow-lg overflow-hidden">
            <div className="p-6 h-full flex flex-col justify-between">
              <div className="grid gap-4">
                <div className="flex items-center">
                  <Avatar className="w-12 h-12 mr-4 border-2 border-primary">
                    <AvatarImage
                      src="/placeholder-user.jpg"
                      alt="Dr. Sarah Johnson"
                    />
                    <AvatarFallback>SJ</AvatarFallback>
                  </Avatar>
                  <div>
                    <h3 className="text-lg font-semibold">
                      Dr. Sarah Rurangirwa
                    </h3>
                    <div className="flex items-center">
                      <div className="w-2 h-2 bg-green-500 rounded-full mr-2" />
                      <span className="text-sm text-muted-foreground">
                        Online
                      </span>
                    </div>
                  </div>
                </div>
                <div className="bg-muted rounded-lg p-4">
                  <p className="text-muted-foreground text-sm">
                    Hello, John. I'm ready to start our video consultation. How
                    are you feeling today?
                  </p>
                </div>
              </div>
              <div className="mt-4">
                <div className="flex justify-center bg-blue-900">
                  <a href="../call" >Start Video Call</a>
                </div>
              </div>
            </div>
          </div>
        </div>
      </main>
      <footer className="flex items-center justify-between px-6 py-4 border-t">
        <p className="text-xs text-muted-foreground">
          &copy; 2024 Mental Health Consultation. All rights reserved.
        </p>
        <nav className="flex items-center gap-4">
          <Link
            href="#"
            className="text-xs text-muted-foreground hover:underline"
            prefetch={false}
          >
            Terms of Service
          </Link>
          <Link
            href="#"
            className="text-xs text-muted-foreground hover:underline"
            prefetch={false}
          >
            Privacy Policy
          </Link>
        </nav>
      </footer>
    </div>
  );
}

function MessageSquareIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M21 15a2 2 0 0 1-2 2H7l-4 4V5a2 2 0 0 1 2-2h14a2 2 0 0 1 2 2z" />
    </svg>
  );
}
