/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/vXnk6q9rJaf
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Tenor_Sans } from 'next/font/google'
import { Chivo } from 'next/font/google'

tenor_sans({
  subsets: ['latin'],
  display: 'swap',
})

chivo({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"
import { Avatar, AvatarImage, AvatarFallback } from "@/components/ui/avatar"
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"

export function Page() {
  return (
    <div className="flex flex-col min-h-screen bg-background">
      <header className="flex items-center justify-between px-6 py-4 border-b">
        <Link href="#" className="flex items-center gap-2" prefetch={false}>
          <MessageSquareIcon className="w-6 h-6" />
          <span className="text-lg font-semibold">Chat with Dr. Sarah Johnson</span>
        </Link>
      </header>
      <main className="flex-1 px-4 py-12 md:py-24">
        <div className="max-w-7xl mx-auto">
          <div className="bg-background rounded-lg shadow-lg overflow-hidden h-[600px] flex flex-col">
            <div className="flex-1 overflow-y-auto p-6 space-y-4">
              <div className="flex items-start gap-4">
                <Avatar className="w-10 h-10 border-2 border-primary">
                  <AvatarImage src="/placeholder-user.jpg" alt="Dr. Sarah Johnson" />
                  <AvatarFallback>SJ</AvatarFallback>
                </Avatar>
                <div className="bg-muted rounded-lg p-4 max-w-[80%]">
                  <p className="text-muted-foreground text-sm">
                    Hello, John. I'm here for our chat. How are you feeling today?
                  </p>
                </div>
              </div>
              <div className="flex items-start gap-4 justify-end">
                <div className="bg-primary rounded-lg p-4 max-w-[80%] text-primary-foreground">
                  <p className="text-sm">
                    Hi Dr. Sarah, I'm doing okay, but I've been feeling a bit anxious lately. I was hoping we could talk
                    about some strategies to manage my anxiety.
                  </p>
                </div>
                <Avatar className="w-10 h-10 border-2 border-primary">
                  <AvatarImage src="/placeholder-user.jpg" alt="John Doe" />
                  <AvatarFallback>JD</AvatarFallback>
                </Avatar>
              </div>
              <div className="flex items-start gap-4">
                <Avatar className="w-10 h-10 border-2 border-primary">
                  <AvatarImage src="/placeholder-user.jpg" alt="Dr. Sarah Johnson" />
                  <AvatarFallback>SJ</AvatarFallback>
                </Avatar>
                <div className="bg-muted rounded-lg p-4 max-w-[80%]">
                  <p className="text-muted-foreground text-sm">
                    I'm sorry to hear you've been feeling anxious, John. Let's talk through some techniques that can
                    help you manage your anxiety. First, let's discuss deep breathing exercises...
                  </p>
                </div>
              </div>
              <div className="flex items-start gap-4 justify-end">
                <div className="bg-primary rounded-lg p-4 max-w-[80%] text-primary-foreground">
                  <p className="text-sm">
                    Okay, the deep breathing exercises sound really helpful. I'll be sure to practice those. Is there
                    anything else you recommend?
                  </p>
                </div>
                <Avatar className="w-10 h-10 border-2 border-primary">
                  <AvatarImage src="/placeholder-user.jpg" alt="John Doe" />
                  <AvatarFallback>JD</AvatarFallback>
                </Avatar>
              </div>
            </div>
            <div className="border-t p-4">
              <form className="flex items-center gap-2">
                <Input placeholder="Type your message..." className="flex-1 bg-muted rounded-lg px-4 py-2 text-sm" />
                <Button size="icon">
                  <SendIcon className="w-5 h-5" />
                </Button>
              </form>
            </div>
          </div>
        </div>
      </main>
      <footer className="flex items-center justify-between px-6 py-4 border-t">
        <p className="text-xs text-muted-foreground">&copy; 2024 Mental Health Consultation. All rights reserved.</p>
        <nav className="flex items-center gap-4">
          <Link href="#" className="text-xs text-muted-foreground hover:underline" prefetch={false}>
            Terms of Service
          </Link>
          <Link href="#" className="text-xs text-muted-foreground hover:underline" prefetch={false}>
            Privacy Policy
          </Link>
        </nav>
      </footer>
    </div>
  )
}

function MessageSquareIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M21 15a2 2 0 0 1-2 2H7l-4 4V5a2 2 0 0 1 2-2h14a2 2 0 0 1 2 2z" />
    </svg>
  )
}


function SendIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m22 2-7 20-4-9-9-4Z" />
      <path d="M22 2 11 13" />
    </svg>
  )
}
